import { getStore } from '@netlify/blobs';
import { createPublicKey, createVerify, randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { clientKey, rateLimit } from './_rateLimit.mts';
const scrypt=promisify(scryptCallback);const store=getStore({name:'thulla-game',consistency:'strong'});const SESSION_MS=7*24*60*60*1000;
type User={id:string;username:string;display_name:string;password_hash:string;coins:number;xp:number;level:number;wins:number;losses:number;games_played:number;created_at:string;email?:string;auth_provider?:string;provider_sub?:string};
const json=(body:unknown,status=200,headers:Record<string,string>={})=>Response.json(body,{status,headers:{'cache-control':'no-store',...headers}});const safeName=(v:unknown)=>String(v||'Player').trim().replace(/[^\p{L}\p{N} _-]/gu,'').slice(0,18)||'Player';const safeUsername=(v:unknown)=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,20);const token=()=>randomBytes(32).toString('hex');
async function hashPassword(p:string){const salt=randomBytes(16).toString('hex');const key=await scrypt(p,salt,64);return `${salt}:${Buffer.from(key).toString('hex')}`;}async function verifyPassword(p:string,s:string){const [salt,hex]=String(s).split(':');if(!salt||!hex)return false;const key=await scrypt(p,salt,64),expected=Buffer.from(hex,'hex');return expected.length===key.length&&timingSafeEqual(expected,Buffer.from(key));}async function getUser(id:string){return await store.get(`user:${id}`,{type:'json'}) as User|null;}const profile=(u:User)=>({id:u.id,username:u.username,display_name:u.display_name,coins:u.coins,xp:u.xp,level:u.level,wins:u.wins,losses:u.losses,games_played:u.games_played});
function b64url(s:string){return Buffer.from(s.replace(/-/g,'+').replace(/_/g,'/'),'base64');}
function decodeJwt(token:string){const parts=token.split('.');if(parts.length!==3)throw new Error('Invalid identity token.');return{header:JSON.parse(b64url(parts[0]).toString('utf8')) as Record<string,unknown>,payload:JSON.parse(b64url(parts[1]).toString('utf8')) as Record<string,unknown>,signature:b64url(parts[2]),signingInput:Buffer.from(`${parts[0]}.${parts[1]}`)};}
async function verifyAppleToken(idToken:string){const jwt=decodeJwt(idToken);if(jwt.header.alg!=='ES256'||!jwt.header.kid)throw new Error('Invalid Apple identity token.');const keys=await fetch('https://appleid.apple.com/auth/keys').then(r=>r.json()) as {keys:Array<Record<string,string>>};const jwk=keys.keys.find(k=>k.kid===jwt.header.kid);if(!jwk)throw new Error('Apple signing key not found.');const key=createPublicKey({key:{kty:'EC',crv:'P-256',x:jwk.x,y:jwk.y},format:'jwk'});const verifier=createVerify('SHA256');verifier.update(jwt.signingInput);verifier.end();if(!verifier.verify(key,jwt.signature))throw new Error('Apple identity verification failed.');const p=jwt.payload;const now=Math.floor(Date.now()/1000);const expected=String(process.env.APPLE_CLIENT_ID||'');if(!expected)throw new Error('Apple Sign-In is not configured.');if(p.iss!=='https://appleid.apple.com'||String(p.aud)!==expected||Number(p.exp||0)<=now)throw new Error('Apple identity token is invalid or expired.');if(p.email_verified===false)throw new Error('Apple email is not verified.');return{sub:String(p.sub||''),email:String(p.email||''),name:safeName(p.name||'Player')};}
async function verifyGoogleToken(idToken:string){const expected=String(process.env.GOOGLE_CLIENT_ID||'');if(!expected)throw new Error('Google Sign-In is not configured.');const r=await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${encodeURIComponent(idToken)}`);const p=await r.json() as Record<string,unknown>;if(!r.ok)throw new Error('Google identity verification failed.');if(String(p.aud)!==expected||String(p.iss)!=='https://accounts.google.com')throw new Error('Google identity token is invalid.');if(Number(p.exp||0)<=Math.floor(Date.now()/1000))throw new Error('Google identity token is expired.');if(String(p.email_verified)!=='true')throw new Error('Google email is not verified.');return{sub:String(p.sub||''),email:String(p.email||''),name:safeName(p.name||String(p.email||'Player').split('@')[0])};}
async function providerLogin(provider:'google'|'apple',credential:string){const identity=provider==='google'?await verifyGoogleToken(credential):await verifyAppleToken(credential);if(!identity.sub)throw new Error('Provider did not return a user identifier.');const key=`provider:${provider}:${identity.sub}`;const existing=await store.get(key,{type:'json'}) as {userId:string}|null;if(existing){const u=await getUser(existing.userId);if(!u)throw new Error('Account record is missing.');const t=token();await store.setJSON(`session:${t}`,{userId:u.id,expiresAt:Date.now()+SESSION_MS});return{token:t,profile:profile(u)};}
let u:User|null=null;if(identity.email){const emailRef=await store.get(`email:${identity.email.toLowerCase()}`,{type:'json'}) as {userId:string}|null;if(emailRef)u=await getUser(emailRef.userId);}
if(!u){let base=safeUsername(identity.email.split('@')[0]||`${provider}_${identity.sub.slice(-8)}`)||`${provider}${identity.sub.slice(-8)}`;base=base.slice(0,20);let username=base;for(let i=1;i<1000;i++){if(!(await store.get(`username:${username}`,{type:'json'})))break;const suffix=String(i);username=`${base.slice(0,20-suffix.length)}${suffix}`;}u={id:randomUUID(),username,display_name:safeName(identity.name||username),password_hash:await hashPassword(randomUUID()+randomUUID()),coins:500,xp:0,level:1,wins:0,losses:0,games_played:0,created_at:new Date().toISOString(),email:identity.email||undefined,auth_provider:provider,provider_sub:identity.sub};await store.setJSON(`user:${u.id}`,u);await store.setJSON(`username:${username}`,{userId:u.id});if(identity.email)await store.setJSON(`email:${identity.email.toLowerCase()}`,{userId:u.id});}
await store.setJSON(key,{userId:u.id});const t=token();await store.setJSON(`session:${t}`,{userId:u.id,expiresAt:Date.now()+SESSION_MS});return{token:t,profile:profile(u)};}
export default async(req:Request)=>{try{const action=req.url.split('/').pop()||'';if(req.method==='OPTIONS')return new Response(null,{status:204});const body=req.method==='POST'?await req.json():{};const limited=await rateLimit(`${clientKey(req)}:${action}`,action==='login'||action==='register'||action==='google'||action==='apple');if(!limited.allowed)return json({error:'Too many requests. Please try again later.'},429,{'retry-after':String(limited.retryAfter)});if(action==='register'){const username=safeUsername(body.username),displayName=safeName(body.displayName||username),password=String(body.password||'');if(!/^[a-z0-9_]{3,20}$/.test(username))return json({error:'Username must be 3-20 letters, numbers or underscore.'},400);if(password.length<6)return json({error:'Password must be at least 6 characters.'},400);if(await store.get(`username:${username}`,{type:'json'}))return json({error:'Username already exists.'},409);const u:User={id:randomUUID(),username,display_name:displayName,password_hash:await hashPassword(password),coins:500,xp:0,level:1,wins:0,losses:0,games_played:0,created_at:new Date().toISOString()};await store.setJSON(`user:${u.id}`,u);await store.setJSON(`username:${username}`,{userId:u.id});const t=token();await store.setJSON(`session:${t}`,{userId:u.id,expiresAt:Date.now()+SESSION_MS});return json({token:t,profile:profile(u)},201);}if(action==='login'){const username=safeUsername(body.username),ref=await store.get(`username:${username}`,{type:'json'}) as {userId:string}|null;if(!ref)return json({error:'Invalid username or password.'},401);const u=await getUser(ref.userId);if(!u||!(await verifyPassword(String(body.password||''),u.password_hash)))return json({error:'Invalid username or password.'},401);const t=token();await store.setJSON(`session:${t`,{userId:u.id,expiresAt:Date.now()+SESSION_MS});return json({token:t,profile:profile(u)});}if(action==='google'||action==='apple'){const credential=String(body.credential||'');if(!credential)return json({error:'Missing provider credential.'},400);try{return json(await providerLogin(action,credential));}catch(e){const message=e instanceof Error?e.message:'Provider sign-in failed.';const status=/not configured/i.test(message)?503:401;return json({error:message},status);}}if(action==='me'){const h=req.headers.get('authorization')||'',t=h.replace(/^Bearer\s+/i,'').trim(),s=t?await store.get(`session:${t}`,{type:'json'}) as {userId:string;expiresAt:number}|null:null;if(!s||s.expiresAt<Date.now()){if(t)await store.delete(`session:${t}`);return json({error:'Not signed in.'},401);}const u=await getUser(s.userId);return u?json({profile:profile(u)}):json({error:'Not signed in.'},401);}if(action==='logout'){const h=req.headers.get('authorization')||'',t=h.replace(/^Bearer\s+/i,'').trim();if(t)await store.delete(`session:${t}`);return json({ok:true});}return json({error:'Not found.'},404);}catch(e){console.error('thulla-auth-error',e);return json({error:'Server error.'},500);}};
export const config={path:'/api/auth/:action',method:['GET','POST','OPTIONS']};
