import { getStore } from '@netlify/blobs';
import { randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
const scrypt=promisify(scryptCallback);const store=getStore({name:'thulla-game',consistency:'strong'});
type User={id:string;username:string;display_name:string;password_hash:string;coins:number;xp:number;level:number;wins:number;losses:number;games_played:number;created_at:string};
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'cache-control':'no-store'}});const safeName=(v:unknown)=>String(v||'Player').trim().replace(/[^\p{L}\p{N} _-]/gu,'').slice(0,18)||'Player';const safeUsername=(v:unknown)=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,20);const token=()=>randomUUID().replaceAll('-','')+randomUUID().replaceAll('-','');
async function hashPassword(p:string){const salt=randomBytes(16).toString('hex');const key=await scrypt(p,salt,64);return `${salt}:${Buffer.from(key).toString('hex')}`;}async function verifyPassword(p:string,s:string){const [salt,hex]=String(s).split(':');if(!salt||!hex)return false;const key=await scrypt(p,salt,64),expected=Buffer.from(hex,'hex');return expected.length===key.length&&timingSafeEqual(expected,Buffer.from(key));}async function getUser(id:string){return await store.get(`user:${id}`,{type:'json'}) as User|null;}const profile=(u:User)=>({id:u.id,username:u.username,display_name:u.display_name,coins:u.coins,xp:u.xp,level:u.level,wins:u.wins,losses:u.losses,games_played:u.games_played});
export default async(req:Request)=>{try{const action=req.url.split('/').pop()||'';if(req.method==='OPTIONS')return new Response(null,{status:204});const body=req.method==='POST'?await req.json():{};if(action==='register'){const username=safeUsername(body.username),displayName=safeName(body.displayName||username),password=String(body.password||'');if(!/^[a-z0-9_]{3,20}$/.test(username))return json({error:'Username must be 3-20 letters, numbers or underscore.'},400);if(password.length<6)return json({error:'Password must be at least 6 characters.'},400);if(await store.get(`username:${username}`,{type:'json'}))return json({error:'Username already exists.'},409);const u:User={id:randomUUID(),username,display_name:displayName,password_hash:await hashPassword(password),coins:500,xp:0,level:1,wins:0,losses:0,games_played:0,created_at:new Date().toISOString()};await store.setJSON(`user:${u.id}`,u);await store.setJSON(`username:${username}`,{userId:u.id});const t=token();await store.setJSON(`session:${t}`,{userId:u.id,expiresAt:Date.now()+30*24*60*60*1000});return json({token:t,profile:profile(u)},201);}if(action==='login'){const username=safeUsername(body.username),ref=await store.get(`username:${username}`,{type:'json'}) as {userId:string}|null;if(!ref)return json({error:'Invalid username or password.'},401);const u=await getUser(ref.userId);if(!u||!(await verifyPassword(String(body.password||''),u.password_hash)))return json({error:'Invalid username or password.'},401);const t=token();await store.setJSON(`session:${t}`,{userId:u.id,expiresAt:Date.now()+30*24*60*60*1000});return json({token:t,profile:profile(u)});}if(action==='me'){const h=req.headers.get('authorization')||'',t=h.replace(/^Bearer\s+/i,'').trim(),s=t?await store.get(`session:${t}`,{type:'json'}) as {userId:string;expiresAt:number}|null:null;if(!s||s.expiresAt<Date.now())return json({error:'Not signed in.'},401);const u=await getUser(s.userId);return u?json({profile:profile(u)}):json({error:'Not signed in.'},401);}if(action==='logout'){const h=req.headers.get('authorization')||'',t=h.replace(/^Bearer\s+/i,'').trim();if(t)await store.delete(`session:${t}`);return json({ok:true});}return json({error:'Not found.'},404);}catch(e){console.error('thulla-auth-error',e);return json({error:'Server error.'},500);}};
export const config={path:'/api/auth/:action',method:['GET','POST','OPTIONS']};
