import { getStore } from '@netlify/blobs';
import { randomBytes, randomInt, randomUUID, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
const scrypt=promisify(scryptCallback);
const store=getStore({name:'thulla-game',consistency:'strong'});
const suits=['spades','hearts','diamonds','clubs'] as const;
const ranks=['2','3','4','5','6','7','8','9','10','J','Q','K','A'] as const;
type Card={id:string;rank:string;suit:string}; type Player={id:string;userId:string|null;name:string;ready:boolean;hand:Card[];lastSeen:number};
type Room={code:string;hostId:string;phase:'lobby'|'playing'|'finished';currentPlayerId:string|null;leadSuit:string|null;trick:{playerId:string;card:Card}[];winnerPlayerId:string|null;loserPlayerId:string|null;players:Player[];rewarded:boolean;matchId:string|null;updatedAt:number};
type User={id:string;username:string;display_name:string;password_hash:string;coins:number;xp:number;level:number;wins:number;losses:number;games_played:number;created_at:string}; type Session={userId:string;expiresAt:number};
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'cache-control':'no-store'}}); const safeName=(v:unknown)=>String(v||'Player').trim().replace(/[^\p{L}\p{N} _-]/gu,'').slice(0,18)||'Player'; const safeUsername=(v:unknown)=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,20); const cardId=(rank:string,suit:string)=>`${rank}-${suit}`; const deck=()=>suits.flatMap(s=>ranks.map(r=>({id:cardId(r,s),rank:r,suit:s}))); const shuffle=(input:Card[])=>{const a=[...input];for(let i=a.length-1;i>0;i--){const j=randomInt(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}; const token=()=>randomUUID().replaceAll('-','')+randomUUID().replaceAll('-',''); const readJson=async<T>(key:string)=>await store.get(key,{type:'json'}) as T|null; const writeJson=async(key:string,value:unknown)=>store.setJSON(key,value);
async function hashPassword(password:string){const salt=randomBytes(16).toString('hex');const key=await scrypt(password,salt,64);return `${salt}:${Buffer.from(key).toString('hex')}`;} async function verifyPassword(password:string,stored:string){const [salt,hex]=String(stored).split(':');if(!salt||!hex)return false;const key=await scrypt(password,salt,64),expected=Buffer.from(hex,'hex');return expected.length===key.length&&timingSafeEqual(expected,Buffer.from(key));} const authToken=(req:Request)=>{const h=req.headers.get('authorization')||'';return h.replace(/^Bearer\s+/i,'').trim();};
async function currentUser(req:Request){const t=authToken(req);if(!t)return null;const s=await readJson<Session>(`session:${t}`);if(!s||s.expiresAt<Date.now())return null;return await readJson<User>(`user:${s.userId}`);}
const publicProfile=(u:User)=>({id:u.id,username:u.username,display_name:u.display_name,coins:u.coins,xp:u.xp,level:u.level,wins:u.wins,losses:u.losses,games_played:u.games_played}); const publicRoom=(room:Room,you:string)=>({code:room.code,hostId:room.hostId,phase:room.phase,currentPlayerId:room.currentPlayerId,leadSuit:room.leadSuit,trick:room.trick,winnerPlayerId:room.winnerPlayerId,loserPlayerId:room.loserPlayerId,matchId:room.matchId,players:room.players.map(p=>({id:p.id,name:p.name,ready:p.ready,connected:Date.now()-p.lastSeen<15000,cardCount:p.hand.length})),you,hand:room.players.find(p=>p.id===you)?.hand||[]});
async function uniqueRoom(){let code='';do code=String(randomInt(100000,1000000));while(await readJson<Room>(`room:${code}`));return code;} async function saveRoom(room:Room){room.updatedAt=Date.now();await writeJson(`room:${room.code}`,room);} async function reward(room:Room){if(room.rewarded)return;room.rewarded=true;const matchId=randomUUID();room.matchId=matchId;for(let i=0;i<room.players.length;i++){const p=room.players[i];if(!p.userId)continue;const u=await readJson<User>(`user:${p.userId}`);if(!u)continue;const loser=p.id===room.loserPlayerId;u.coins+=loser?20:50;u.xp+=loser?40:100;u.level=1+Math.floor(u.xp/1000);u.wins+=loser?0:1;u.losses+=loser?1:0;u.games_played++;await writeJson(`user:${u.id}`,u);await writeJson(`match:${matchId}:${u.id}`,{matchId,roomCode:room.code,playedAt:new Date().toISOString(),finishPosition:loser?room.players.length:i+1,coinsDelta:loser?20:50,xpDelta:loser?40:100,winnerUsername:room.players.find(x=>x.id!==room.loserPlayerId)?.name||null});}await saveRoom(room);}
function legal(card:Card,hand:Card[],lead:string|null){return !lead||card.suit===lead||!hand.some(c=>c.suit===lead);} async function handle(req:Request){if(req.method==='OPTIONS')return new Response(null,{status:204});let body:any={};if(req.method!=='GET'){try{body=await req.json();}catch{return json({error:'Invalid JSON.'},400);}}const action=String(body.action||'');
if(action==='register'){const username=safeUsername(body.username),displayName=safeName(body.displayName||username),password=String(body.password||'');if(!/^[a-z0-9_]{3,20}$/.test(username))return json({error:'Username must be 3-20 letters, numbers or underscore.'},400);if(password.length<6)return json({error:'Password must be at least 6 characters.'},400);if(await readJson<{userId:string}>(`username:${username}`))return json({error:'Username already exists.'},409);const u:User={id:randomUUID(),username,display_name:displayName,password_hash:await hashPassword(password),coins:500,xp:0,level:1,wins:0,losses:0,games_played:0,created_at:new Date().toISOString()};await writeJson(`user:${u.id}`,u);await writeJson(`username:${username}`,{userId:u.id});const t=token();await writeJson(`session:${t}`,{userId:u.id,expiresAt:Date.now()+2592000000});return json({token:t,profile:publicProfile(u)},201);}
if(action==='login'){const username=safeUsername(body.username),ref=await readJson<{userId:string}>(`username:${username}`);if(!ref)return json({error:'Invalid username or password.'},401);const u=await readJson<User>(`user:${ref.userId}`);if(!u||!(await verifyPassword(String(body.password||''),u.password_hash)))return json({error:'Invalid username or password.'},401);const t=token();await writeJson(`session:${t}`,{userId:u.id,expiresAt:Date.now()+2592000000});return json({token:t,profile:publicProfile(u)});}if(action==='me'){const u=await currentUser(req);return u?json({profile:publicProfile(u)}):json({error:'Not signed in.'},401);}if(action==='logout'){const t=authToken(req);if(t)await store.delete(`session:${t}`);return json({ok:true});}if(action==='leaderboard'){const {blobs}=await store.list({prefix:'user:'});const users:User[]=[];for(const b of blobs.slice(0,500)){const u=await readJson<User>(b.key);if(u?.games_played)users.push(u);}users.sort((a,b)=>b.wins-a.wins||b.xp-a.xp||a.games_played-b.games_played);return json({players:users.slice(0,100).map((u,i)=>({...publicProfile(u),rank:i+1}))});}
const user=await currentUser(req);if(!user)return json({error:'Sign in required.'},401);if(action==='profile')return json({profile:publicProfile(user)});if(action==='matches'){const {blobs}=await store.list({prefix:'match:'});const rows=[];for(const b of blobs){if(!b.key.endsWith(`:${user.id}`))continue;const m=await readJson<any>(b.key);if(m)rows.push(m);}rows.sort((a,b)=>String(b.playedAt).localeCompare(String(a.playedAt)));return json({matches:rows.slice(0,50)});}
if(action==='create_room'){const code=await uniqueRoom(),p:Player={id:randomUUID(),userId:user.id,name:user.display_name,ready:false,hand:[],lastSeen:Date.now()};const room:Room={code,hostId:p.id,phase:'lobby',currentPlayerId:null,leadSuit:null,trick:[],winnerPlayerId:null,loserPlayerId:null,players:[p],rewarded:false,matchId:null,updatedAt:Date.now()};await saveRoom(room);return json({state:publicRoom(room,p.id)});}
const code=String(body.code||'').trim();const room=await readJson<Room>(`room:${code}`);if(!room)return json({error:'Room not found.'},404);let player=room.players.find(p=>p.userId===user.id);if(action==='join_room'&&!player){if(room.phase!=='lobby')return json({error:'Game already started.'},409);if(room.players.length>=5)return json({error:'Room is full.'},409);player={id:randomUUID(),userId:user.id,name:user.display_name,ready:false,hand:[],lastSeen:Date.now()};room.players.push(player);await saveRoom(room);return json({state:publicRoom(room,player.id)});}if(!player)return json({error:'You are not in this room.'},403);player.lastSeen=Date.now();if(action==='state'){await saveRoom(room);return json({state:publicRoom(room,player.id)});}if(action==='ready'){if(room.phase!=='lobby')return json({error:'Game already started.'},409);player.ready=!player.ready;await saveRoom(room);return json({state:publicRoom(room,player.id)});}if(action==='start_game'){if(room.hostId!==player.id)return json({error:'Only the host can start.'},403);if(room.players.length<3||!room.players.every(p=>p.ready))return json({error:'Need 3-5 players and everyone ready.'},400);const d=shuffle(deck());room.players.forEach((p,i)=>{p.hand=d.filter((_,ci)=>ci%room.players.length===i);p.ready=false;});const starter=room.players.find(p=>p.hand.some(c=>c.id==='2-clubs'))||room.players[0];room.phase='playing';room.currentPlayerId=starter.id;room.leadSuit=null;room.trick=[];room.winnerPlayerId=null;room.loserPlayerId=null;room.rewarded=false;room.matchId=null;await saveRoom(room);return json({state:publicRoom(room,player.id)});}
if(action==='play_card'){if(room.phase!=='playing')return json({error:'Game is not active.'},409);if(room.currentPlayerId!==player.id)return json({error:'It is not your turn.'},409);const idx=player.hand.findIndex(c=>c.id===String(body.cardId));if(idx<0)return json({error:'Card is not in your hand.'},400);const card=player.hand[idx];if(!legal(card,player.hand,room.leadSuit))return json({error:`You must follow ${room.leadSuit}.`},400);player.hand.splice(idx,1);room.leadSuit ||= card.suit;room.trick.push({playerId:player.id,card});if(room.trick.length<room.players.length){const pi=room.players.findIndex(p=>p.id===player.id);room.currentPlayerId=room.players[(pi+1)%room.players.length].id;}else{const candidates=room.trick.filter(x=>x.card.suit===room.leadSuit);const win=candidates.reduce((a,b)=>ranks.indexOf(b.card.rank)>ranks.indexOf(a.card.rank)?b:a);room.winnerPlayerId=win.playerId;room.trick=[];room.leadSuit=null;room.currentPlayerId=win.playerId;if(room.players.every(p=>p.hand.length===0)){room.phase='finished';room.loserPlayerId=win.playerId;}}await saveRoom(room);if(room.phase==='finished')await reward(room);return json({state:publicRoom(room,player.id)});}
if(action==='leave'){room.players=room.players.filter(p=>p.id!==player.id);if(room.players.length===0){await store.delete(`room:${room.code}`);return json({left:true});}if(room.hostId===player.id)room.hostId=room.players[0].id;await saveRoom(room);return json({left:true});}return json({error:'Unknown action.'},400);}
export default async(req:Request)=>{try{return await handle(req);}catch(error){console.error('thulla-function-error',error);return json({error:'Server error.'},500);}};export const config={path:'/api/game',method:['GET','POST','OPTIONS']};
