type GoogleCredentialResponse = { credential?: string };
type ProviderProfile = { token: string };
const GOOGLE_CLIENT_ID = String(import.meta.env.VITE_GOOGLE_CLIENT_ID || '');
const APPLE_CLIENT_ID = String(import.meta.env.VITE_APPLE_CLIENT_ID || '');
const APPLE_REDIRECT_URI = String(import.meta.env.VITE_APPLE_REDIRECT_URI || window.location.origin + '/');
let mounted = false;
function setMessage(message: string) { const existing = document.querySelector<HTMLElement>('[data-provider-message]'); if (existing) existing.textContent = message; }
async function providerLogin(provider: 'google' | 'apple', credential: string): Promise<ProviderProfile> { const response = await fetch(`/api/auth/${provider}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ credential }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || `${provider} sign-in failed.`); return data; }
async function googleCredential(response: GoogleCredentialResponse) { try { if (!response.credential) throw new Error('Google did not return an account credential.'); const data = await providerLogin('google', response.credential); localStorage.setItem('thulla_auth_token', data.token); setMessage('Google account connected. Opening your game…'); window.location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Google sign-in failed.'); } }
function loadScript(src: string, id: string): Promise<void> { const existing = document.getElementById(id) as HTMLScriptElement | null; if (existing) return existing.dataset.loaded === '1' ? Promise.resolve() : new Promise((resolve, reject) => { existing.addEventListener('load', () => resolve(), { once: true }); existing.addEventListener('error', () => reject(new Error('Authentication provider failed to load.')), { once: true }); }); return new Promise((resolve, reject) => { const script = document.createElement('script'); script.id = id; script.src = src; script.async = true; script.defer = true; script.onload = () => { script.dataset.loaded = '1'; resolve(); }; script.onerror = () => reject(new Error('Authentication provider failed to load.')); document.head.appendChild(script); }); }
async function signInGoogle() { if (!GOOGLE_CLIENT_ID) { setMessage('Google Sign-In is ready, but the Google Client ID is not configured on this deployment.'); return; } try { setMessage('Opening your Google accounts…'); await loadScript('https://accounts.google.com/gsi/client', 'thulla-google-gsi'); const google = (window as any).google; if (!google?.accounts?.id) throw new Error('Google Sign-In could not initialize.'); google.accounts.id.initialize({ client_id: GOOGLE_CLIENT_ID, callback: googleCredential, auto_select: false, cancel_on_tap_outside: true }); google.accounts.id.prompt(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Google sign-in failed.'); } }
async function signInApple() { if (!APPLE_CLIENT_ID) { setMessage('Apple Sign-In is ready, but the Apple Services ID is not configured on this deployment.'); return; } try { setMessage('Opening Apple Account sign-in…'); await loadScript('https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js', 'thulla-apple-js'); const AppleID = (window as any).AppleID; if (!AppleID?.auth) throw new Error('Apple Sign-In could not initialize.'); AppleID.auth.init({ clientId: APPLE_CLIENT_ID, scope: 'name email', redirectURI: APPLE_REDIRECT_URI, usePopup: true }); const result = await AppleID.auth.signIn(); const credential = result?.authorization?.id_token; if (!credential) throw new Error('Apple did not return an identity credential.'); const data = await providerLogin('apple', credential); localStorage.setItem('thulla_auth_token', data.token); setMessage('Apple Account connected. Opening your game…'); window.location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Apple sign-in failed.'); } }
function mount() { if (mounted) return; const card = document.querySelector<HTMLElement>('.account-card'); const tabs = card?.querySelector<HTMLElement>('.account-tabs'); if (!card || !tabs) return; mounted = true; const social = document.createElement('div'); social.className = 'social-auth'; social.innerHTML = `<button type="button" class="social-button google-button">Continue with Google</button><button type="button" class="social-button apple-button">Continue with Apple</button><div class="provider-or"><span>OR</span></div><div class="provider-message" data-provider-message>Use Google or Apple to create/sign in to your player account.</div>`; tabs.insertAdjacentElement('afterend', social); social.querySelector<HTMLButtonElement>('.google-button')?.addEventListener('click', signInGoogle); social.querySelector<HTMLButtonElement>('.apple-button')?.addEventListener('click', signInApple); }
const observer = new MutationObserver(mount); observer.observe(document.documentElement, { childList: true, subtree: true }); mount();
