const AUTH_KEY='thulla-auth-token';
const STYLE_ID='thulla-history-style';
const PANEL_ID='thulla-history-panel';

type Match={matchId:string;roomCode:string;playedAt:string;finishPosition:number;coinsDelta:number;xpDelta:number;winnerUsername:string|null};

const css=`#${PANEL_ID}{position:fixed;inset:0;z-index:100;display:none;place-items:center;padding:18px;background:rgba(0,0,0,.72);backdrop-filter:blur(6px)}#${PANEL_ID}.open{display:grid}.th-history-card{width:min(520px,100%);max-height:min(760px,calc(100dvh - 36px));overflow:auto;background:#06130d;color:#f5f7f4;border:1px solid #426a55;border-radius:24px;padding:22px;box-shadow:0 30px 90px #000b}.th-history-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:16px}.th-history-head h2{margin:0;font-size:21px}.th-history-close{width:40px;height:40px;border-radius:50%;border:1px solid #315542;background:#0b1b13;color:#d9e4de;font-size:23px}.th-history-list{display:grid;gap:9px}.th-history-row{display:grid;grid-template-columns:48px 1fr auto;gap:11px;align-items:center;padding:12px;border:1px solid #234332;background:#091b12;border-radius:13px}.th-history-icon{width:42px;height:42px;border-radius:12px;display:grid;place-items:center;background:#10281b;color:#d8ad4a;font-weight:800}.th-history-row strong{display:block;font-size:12px}.th-history-row small{display:block;color:#789486;font-size:9px;margin-top:4px}.th-history-result{font-size:10px;font-weight:800;text-align:right}.th-win{color:#7de1a0}.th-loss{color:#e99b9b}.th-finish{color:#d8ad4a}.th-history-reward{margin-top:3px;color:#f0c65b!important}.th-history-empty{text-align:center;color:#789486;padding:35px 15px;border:1px dashed #315542;border-radius:13px}.th-history-error{color:#ffb2b2;background:#351919;border:1px solid #743838;border-radius:10px;padding:11px;font-size:10px}.th-history-loading{text-align:center;color:#789486;padding:30px}.th-history-trigger{position:fixed;right:14px;bottom:max(18px,env(safe-area-inset-bottom));z-index:40;border:1px solid #d8ad4a;background:#d8ad4a;color:#172116;border-radius:999px;padding:11px 15px;font-weight:800;box-shadow:0 10px 30px #0008;min-height:44px}.th-history-trigger[hidden]{display:none}@media(min-width:701px){.th-history-trigger{right:24px;bottom:24px}}@media(max-width:380px){.th-history-trigger{right:10px;padding:10px 12px;font-size:11px}}`;

function ensureStyle(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=css;document.head.appendChild(s)}
function esc(v:string){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||c))}
function formatDate(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?'Unknown date':d.toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}
function resultFor(m:Match){if(m.finishPosition===1)return ['WIN','th-win'];if(m.finishPosition>1&&m.coinsDelta===20)return ['BHABHI','th-loss'];return [`#${m.finishPosition} FINISH`,'th-finish']}
async function loadMatches(panel:HTMLElement){const list=panel.querySelector<HTMLElement>('[data-history-list]')!;list.innerHTML='<div class="th-history-loading">Loading match history…</div>';const token=localStorage.getItem(AUTH_KEY);if(!token){list.innerHTML='<div class="th-history-empty">Sign in to view your match history.</div>';return}try{const r=await fetch('/api/game',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({action:'matches'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load history.');const matches=(d.matches||[]) as Match[];if(!matches.length){list.innerHTML='<div class="th-history-empty"><strong>No matches yet</strong><br>Complete your first game and it will appear here.</div>';return}list.innerHTML=matches.map(m=>{const[result,cls]=resultFor(m);return `<article class="th-history-row"><div class="th-history-icon">${result==='WIN'?'🏆':'🃏'}</div><div><strong>Room #${esc(m.roomCode)}</strong><small>${esc(formatDate(m.playedAt))} · Match ${esc(m.matchId.slice(0,8))}</small><small class="th-history-reward">🪙 +${m.coinsDelta} · ✦ +${m.xpDelta} XP${m.winnerUsername?` · Winner: ${esc(m.winnerUsername)}`:''}</small></div><div class="th-history-result ${cls}">${result}</div></article>`}).join('')}catch(e){list.innerHTML=`<div class="th-history-error">${esc(e instanceof Error?e.message:'Unable to load match history.')}</div>`}}
function mount(){ensureStyle();if(document.getElementById(PANEL_ID))return;const trigger=document.createElement('button');trigger.className='th-history-trigger';trigger.type='button';trigger.textContent='📜 History';trigger.setAttribute('aria-label','Open match history');document.body.appendChild(trigger);const panel=document.createElement('div');panel.id=PANEL_ID;panel.innerHTML='<section class="th-history-card" role="dialog" aria-modal="true" aria-labelledby="th-history-title"><div class="th-history-head"><div><h2 id="th-history-title">Match History</h2><small>Recent completed matches</small></div><button class="th-history-close" type="button" aria-label="Close match history">×</button></div><div class="th-history-list" data-history-list></div></section>';document.body.appendChild(panel);const close=()=>panel.classList.remove('open');trigger.addEventListener('click',()=>{panel.classList.add('open');void loadMatches(panel)});panel.querySelector('.th-history-close')!.addEventListener('click',close);panel.addEventListener('click',e=>{if(e.target===panel)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});window.addEventListener('storage',e=>{if(e.key===AUTH_KEY&&!localStorage.getItem(AUTH_KEY))trigger.hidden=true});trigger.hidden=!localStorage.getItem(AUTH_KEY)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
