import './home-10-3.css';

type Profile={id:string;username:string;display_name:string;coins:number;xp:number;level:number;wins:number;losses:number;games_played:number};
const authKey='thulla-auth-token';
const sessionKey='thulla-multiplayer-session';
const api='/api/game';
const esc=(v:string)=>v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||c));
async function me():Promise<Profile|null>{const token=localStorage.getItem(authKey);if(!token)return null;const r=await fetch('/api/auth/me',{headers:{authorization:`Bearer ${token}`}});if(!r.ok)return null;return (await r.json()).profile as Profile;}
async function game(action:string,extra:Record<string,unknown>={}){const token=localStorage.getItem(authKey)||'';const r=await fetch(api,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({action,...extra})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Game request failed.');return d;}
function mount(p:Profile){if(document.querySelector('.home103-overlay'))return;const root=document.getElementById('root');if(!root)return;const overlay=document.createElement('div');overlay.className='home103-overlay';overlay.innerHTML=`<section class="home103-card"><header class="home103-header"><div><div class="home103-brand">THULLA <span>MASTER</span></div><div class="home103-sub">ONLINE MULTIPLAYER CARD GAME</div></div><button class="home103-settings" aria-label="Settings">⚙</button></header><button class="home103-profile" data-action="profile"><div class="home103-avatar">${esc(p.display_name.charAt(0).toUpperCase()||'?')}</div><div class="home103-identity"><strong>${esc(p.display_name)}</strong><span>@${esc(p.username)} · LEVEL ${p.level}</span></div><div class="home103-coins">🪙 ${p.coins}</div><b>›</b></button><div class="home103-status"><i></i> Server connected</div><button class="home103-primary" data-action="create"><span>♠</span><div><strong>PLAY ONLINE</strong><small>Enter a live multiplayer table</small></div><b>›</b></button><div class="home103-grid"><button data-action="friends"><span>👥</span><strong>Friends</strong><small>Invite players</small></button><button data-action="history"><span>📜</span><strong>Match History</strong><small>Recent games</small></button><button data-action="rewards"><span>🎁</span><strong>Daily Rewards</strong><small>Coming next</small></button><button data-action="shop"><span>🪙</span><strong>Coin Shop</strong><small>Coming next</small></button></div><div class="home103-private"><div><strong>Private Room</strong><span>Join with a 6-digit code</span></div><div class="home103-join"><input inputmode="numeric" maxlength="6" placeholder="123456" aria-label="Room code"/><button data-action="join">JOIN</button></div></div><div class="home103-stats"><span><b>${p.xp}</b> XP</span><span><b>${p.wins}</b> WINS</span><span><b>${p.games_played}</b> GAMES</span></div><p class="home103-note">3–5 players · Secure server game · Private room codes</p></section>`;root.appendChild(overlay);
 const msg=(text:string)=>{let t=overlay.querySelector('.home103-toast') as HTMLElement|null;if(!t){t=document.createElement('div');t.className='home103-toast';overlay.appendChild(t)}t.textContent=text;t.classList.add('show');setTimeout(()=>t?.classList.remove('show'),2400)};
 overlay.addEventListener('click',async e=>{const el=(e.target as HTMLElement).closest('[data-action]') as HTMLElement|null;if(!el)return;const action=el.dataset.action;if(action==='profile'){overlay.remove();return;}if(action==='create'){try{const d=await game('create_room');localStorage.setItem(sessionKey,JSON.stringify({code:d.state.code}));overlay.remove();location.reload();}catch(err){msg(err instanceof Error?err.message:'Unable to create room.')}}if(action==='join'){const input=overlay.querySelector('input') as HTMLInputElement;if(!/^\d{6}$/.test(input.value))return msg('Enter a 6-digit room code.');try{const d=await game('join_room',{code:input.value});localStorage.setItem(sessionKey,JSON.stringify({code:d.state.code}));overlay.remove();location.reload();}catch(err){msg(err instanceof Error?err.message:'Unable to join room.')}}if(action==='friends'||action==='rewards'||action==='shop')msg('This feature is scheduled for the next phase.');if(action==='history'){msg('Opening match history…');setTimeout(()=>{location.hash='matches';overlay.remove();},300)}});
 const code=overlay.querySelector('input') as HTMLInputElement;code?.addEventListener('input',()=>{code.value=code.value.replace(/\D/g,'').slice(0,6)});
}
(async()=>{const p=await me();if(!p)return;const start=()=>{const lobby=document.querySelector('.lobby-card');if(lobby&&document.querySelector('.profile-strip'))mount(p)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();})();