type GoogleCredentialResponse={credential:string};
type GoogleApi={accounts:{id:{initialize:(config:{client_id:string,callback:(response:GoogleCredentialResponse)=>void,auto_select?:boolean,use_fedcm_for_button?:boolean})=>void;renderButton:(parent:HTMLElement,options:Record<string,unknown>)=>void;prompt:()=>void}}};
declare global{interface Window{google?:GoogleApi;AppleID?:{auth:{init:(config:Record<string,unknown>)=>void;signIn:()=>Promise<{authorization?:{id_token?:string}}>} }}}

const GOOGLE_CLIENT_ID=String((import.meta as any).env?.VITE_GOOGLE_CLIENT_ID||'').trim();
const APPLE_CLIENT_ID=String((import.meta as any).env?.VITE_APPLE_CLIENT_ID||'').trim();
const APPLE_REDIRECT_URI=String((import.meta as any).env?.VITE_APPLE_REDIRECT_URI||window.location.origin+'/').trim();
const AUTH_TOKEN_KEY='thulla-auth-token';
let busy=false;

function loadScript(src:string){return new Promise<void>((resolve,reject)=>{const existing=document.querySelector(`script[src="${src}"]`);if(existing){if((existing as HTMLScriptElement).dataset.loaded==='1')return resolve();existing.addEventListener('load',()=>resolve(),{once:true});existing.addEventListener('error',()=>reject(new Error('Unable to load sign-in provider.')),{once:true});return;}const s=document.createElement('script');s.src=src;s.async=true;s.onload=()=>{s.dataset.loaded='1';resolve()};s.onerror=()=>reject(new Error('Unable to load sign-in provider.'));document.head.appendChild(s);});}
function message(text:string){let el=document.querySelector<HTMLElement>('.provider-message');if(!el){el=document.createElement('div');el.className='provider-message';document.querySelector('.account-tabs')?.after(el);}el.textContent=text;el.style.display='block';}
async function finishProvider(provider:'google'|'apple',credential:string){if(!credential||busy)return;busy=true;message('Connecting your account…');try{const r=await fetch(`/api/auth/${provider}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({credential})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Sign-in failed.');localStorage.setItem(AUTH_TOKEN_KEY,data.token);window.location.reload();}catch(e){message(e instanceof Error?e.message:'Sign-in failed.');busy=false;}}
function addProviderArea(){const tabs=document.querySelector('.account-tabs');if(!tabs||document.querySelector('.provider-auth'))return;const wrap=document.createElement('div');wrap.className='provider-auth';wrap.innerHTML='<div class="provider-divider"><span>OR CONTINUE WITH</span></div><div class="provider-buttons"><div class="provider-google" aria-label="Continue with Google"></div><button type="button" class="provider-apple" aria-label="Continue with Apple"><span class="apple-mark"></span><span>Continue with Apple</span></button></div>';
tabs.after(wrap);
const googleHost=wrap.querySelector<HTMLElement>('.provider-google')!;
const appleButton=wrap.querySelector<HTMLButtonElement>('.provider-apple')!;
if(GOOGLE_CLIENT_ID){loadScript('https://accounts.google.com/gsi/client').then(()=>{if(!window.google)return;window.google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:r=>finishProvider('google',r.credential),use_fedcm_for_button:true});window.google.accounts.id.renderButton(googleHost,{type:'standard',theme:'outline',size:'large',text:'continue_with',shape:'rectangular',logo_alignment:'left',width:googleHost.clientWidth||360});}).catch(()=>message('Google sign-in is temporarily unavailable.'));}else{googleHost.innerHTML='<button type="button" class="provider-fallback provider-google-fallback">Continue with Google</button>';googleHost.querySelector('button')?.addEventListener('click',()=>message('Google Sign-In is not configured yet. Add VITE_GOOGLE_CLIENT_ID in Netlify environment variables.'));}
if(APPLE_CLIENT_ID){appleButton.addEventListener('click',async()=>{if(busy)return;try{await loadScript('https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js');if(!window.AppleID)throw new Error('Apple Sign-In is unavailable.');window.AppleID.auth.init({clientId:APPLE_CLIENT_ID,scope:'name email',redirectURI:APPLE_REDIRECT_URI,usePopup:true});const result=await window.AppleID.auth.signIn();const idToken=result.authorization?.id_token;if(!idToken)throw new Error('Apple did not return an identity token.');await finishProvider('apple',idToken);}catch(e){message(e instanceof Error?e.message:'Apple Sign-In was cancelled.');}});}else{appleButton.addEventListener('click',()=>message('Apple Sign-In is not configured yet. Add VITE_APPLE_CLIENT_ID in Netlify environment variables.'));}}
function watch(){addProviderArea();const observer=new MutationObserver(()=>addProviderArea());observer.observe(document.getElementById('root')||document.body,{childList:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch,{once:true});else watch();
